baseURL = "https://aruhpy.github.io/io/"
languageCode = "ko-kr"
title = "나루"
theme = "naru"

relativeURLs = true
canonifyURLs = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
